version: '2'
services:
  flask:
    build: .
    ports:
      - '80:5000'
    volumes:
      - ./:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=True
  postgres:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db : {}
