version: '2'
services:
  flask:
    build: ./
    image: flask
    command: 'python devServerFailsafe.py'
    ports:
      - '80:5000'
    volumes:
      - ./:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=True
  postgres:
    build: ./Postgres/
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db : {}
