"""empty message

Revision ID: 3384af47c7c1
Revises: f233a90277d7
Create Date: 2016-04-20 16:47:53.742560

"""

# revision identifiers, used by Alembic.
revision = '3384af47c7c1'
down_revision = 'f233a90277d7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coffee_shops', sa.Column('services', postgresql.JSONB(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coffee_shops', 'services')
    ### end Alembic commands ###
