"""empty message

Revision ID: 9ed9a56f040f
Revises: 
Create Date: 2016-04-19 16:34:11.903686

"""

# revision identifiers, used by Alembic.
revision = '9ed9a56f040f'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffee_shops',
    sa.Column('id_coffee_shop', postgresql.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('currency', postgresql.ENUM('eur', 'gpb', name='currency'), nullable=False),
    sa.Column('swift', sa.String(length=20), nullable=False),
    sa.Column('iban', sa.String(length=20), nullable=False),
    sa.Column('transaction_account', sa.Text(), nullable=False),
    sa.Column('latitude', sa.REAL(), nullable=True),
    sa.Column('longitude', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id_coffee_shop'),
    sa.UniqueConstraint('transaction_account'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coffee_shops')
    op.execute("DROP TYPE currency;")
    ### end Alembic commands ###
