"""empty message

Revision ID: c3b94135f762
Revises: 473404d1e038
Create Date: 2016-04-19 20:12:20.139686

"""

# revision identifiers, used by Alembic.
revision = 'c3b94135f762'
down_revision = '473404d1e038'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('json', postgresql.JSONB(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'json')
    ### end Alembic commands ###
